# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1071, 876)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/me.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidget_project = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_project.sizePolicy().hasHeightForWidth())
        self.tableWidget_project.setSizePolicy(sizePolicy)
        self.tableWidget_project.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_project.setAlternatingRowColors(False)
        self.tableWidget_project.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_project.setObjectName(_fromUtf8("tableWidget_project"))
        self.tableWidget_project.setColumnCount(1)
        self.tableWidget_project.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_project.setHorizontalHeaderItem(0, item)
        self.tableWidget_project.horizontalHeader().setHighlightSections(False)
        self.tableWidget_project.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_project.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tableWidget_project)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget_left = QtGui.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget_left.setFont(font)
        self.treeWidget_left.setObjectName(_fromUtf8("treeWidget_left"))
        self.verticalLayout_2.addWidget(self.treeWidget_left)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeWidget_right = QtGui.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeWidget_right.setFont(font)
        self.treeWidget_right.setObjectName(_fromUtf8("treeWidget_right"))
        self.verticalLayout.addWidget(self.treeWidget_right)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.lineEdit_l = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        self.lineEdit_l.setFont(font)
        self.lineEdit_l.setObjectName(_fromUtf8("lineEdit_l"))
        self.verticalLayout_3.addWidget(self.lineEdit_l)
        self.lineEdit_r = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        self.lineEdit_r.setFont(font)
        self.lineEdit_r.setObjectName(_fromUtf8("lineEdit_r"))
        self.verticalLayout_3.addWidget(self.lineEdit_r)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_new = QtGui.QAction(MainWindow)
        self.action_new.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new.setIcon(icon1)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("res/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon2)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_del_scene = QtGui.QAction(MainWindow)
        self.action_del_scene.setCheckable(False)
        self.action_del_scene.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("res/del.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_del_scene.setIcon(icon3)
        self.action_del_scene.setObjectName(_fromUtf8("action_del_scene"))
        self.action_left = QtGui.QAction(MainWindow)
        self.action_left.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_left.setIcon(icon4)
        self.action_left.setObjectName(_fromUtf8("action_left"))
        self.action_right = QtGui.QAction(MainWindow)
        self.action_right.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("res/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_right.setIcon(icon5)
        self.action_right.setObjectName(_fromUtf8("action_right"))
        self.action_test_xpath = QtGui.QAction(MainWindow)
        self.action_test_xpath.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("res/test_xpath.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_test_xpath.setIcon(icon6)
        self.action_test_xpath.setObjectName(_fromUtf8("action_test_xpath"))
        self.action_dump_scene = QtGui.QAction(MainWindow)
        self.action_dump_scene.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("res/dump.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_dump_scene.setIcon(icon7)
        self.action_dump_scene.setObjectName(_fromUtf8("action_dump_scene"))
        self.toolBar.addAction(self.action_new)
        self.toolBar.addAction(self.action_open)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_dump_scene)
        self.toolBar.addAction(self.action_del_scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_left)
        self.toolBar.addAction(self.action_right)
        self.toolBar.addAction(self.action_test_xpath)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ztgt-scene-analyse", None))
        item = self.tableWidget_project.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "场景", None))
        self.treeWidget_left.headerItem().setText(0, _translate("MainWindow", "[]tag", None))
        self.treeWidget_left.headerItem().setText(1, _translate("MainWindow", "attrib", None))
        self.treeWidget_right.headerItem().setText(0, _translate("MainWindow", "[]tag", None))
        self.treeWidget_right.headerItem().setText(1, _translate("MainWindow", "attribs", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_new.setText(_translate("MainWindow", "新建", None))
        self.action_new.setToolTip(_translate("MainWindow", "新建工程", None))
        self.action_open.setText(_translate("MainWindow", "打开", None))
        self.action_open.setToolTip(_translate("MainWindow", "打开工程", None))
        self.action_del_scene.setText(_translate("MainWindow", "删除编辑场景", None))
        self.action_left.setText(_translate("MainWindow", "左边", None))
        self.action_right.setText(_translate("MainWindow", "右边", None))
        self.action_test_xpath.setText(_translate("MainWindow", "测试XPath", None))
        self.action_dump_scene.setText(_translate("MainWindow", "Dump", None))

